export const ZONES=[
    ["a1-cold-plains",["Cold Plains","The Cave","Cave Level 1","Cave Level 2"]],["a1-burial",["Burial Grounds","Crypt","Mausoleum"]],["a1-stony",["Stony Field","Tristram"]],["a1-dark",["Dark Wood","Underground Passage Level 1","Underground Passage Level 2","Underground Passage"]],["a1-black",["Black Marsh","The Hole","Hole Level 1","Hole Level 2","Forgotten Tower","Tower Cellar"]],["a1-jail",["Jail","Barracks"]],["a1-pit",["The Pit","Pit Level 1","Pit Level 2","Tamoe Highland","Outer Cloister"]],["a1-cathedral",["Inner Cloister","Cathedral","Catacombs"]],["a1-cow",["Moo Moo Farm","The Secret Cow Level","Secret Cow Level"]],
    ["a2-sewers",["Sewers Level 1","Sewers Level 2","Sewers Level 3","Lut Gholein Sewers"]],["a2-rocky",["Rocky Waste","Stony Tomb","Stony Tomb Level 1","Stony Tomb Level 2"]],["a2-dry",["Dry Hills","Halls of the Dead"]],["a2-oasis",["Far Oasis","Maggot Lair"]],["a2-lost",["Lost City","Valley of Snakes","Claw Viper Temple","Ancient Tunnels"]],["a2-palace",["Harem","Palace Cellar","Arcane Sanctuary"]],["a2-canyon",["Canyon of the Magi","Tal Rasha's Tomb","Tal Rashas Tomb","Tal Rasha’s Tomb"]],
    ["a3-spider",["Spider Forest","Spider Cavern","Arachnid Lair"]],["a3-marsh",["Great Marsh"]],["a3-flayer",["Flayer Jungle","Flayer Dungeon","Swampy Pit"]],["a3-kurast",["Lower Kurast","Kurast Bazaar","Upper Kurast","Kurast Causeway","Ruined Temple","Disused Fane"]],["a3-trav",["Travincal"]],["a3-durance",["Durance of Hate"]],
    ["a4-steppes",["Outer Steppes","Plains of Despair"]],["a4-river",["City of the Damned","River of Flame"]],["a4-chaos",["Chaos Sanctuary","The Chaos Sanctuary"]],
    ["a5-foothills",["Bloody Foothills","Frigid Highlands","Abaddon","Abbadon"]],["a5-glacial",["Glacial Trail","Drifter Cavern"]],["a5-crystal",["Crystalline Passage","Frozen River"]],["a5-tundra",["Frozen Tundra","Infernal Pit"]],["a5-arreat",["Arreat Plateau","Pit of Acheron"]],["a5-temple",["Nihlathak's Temple","Nihlathak’s Temple","Halls of Anguish","Halls of Pain","Halls of Vaught","Temple Halls"]],["a5-ancients",["Ancient's Way","Ancients' Way","The Ancients' Way","Icy Cellar"]],["a5-worldstone",["Worldstone Keep Level 1","Worldstone Keep Level 2","Worldstone Keep Level 3","Worldstone Keep","Throne of Destruction","Worldstone Chamber"]]
  ];

ZONES.push(["a1-blood-moor",["Blood Moor","Den of Evil"]]);
